_BASE_: "base.yml"
MODEL:
  BASE: 'BASE_UDA'
  HEADS:
    NUM_CLASSES: 2000
    MARGIN: 0.35
    SCALE: 60
  LOSSES:
    CE:
      EPSILON: 0.005
    KL:
      SCALE: 0.01
    SIM:
      SCALE: 0.05
INPUT:
  DO_AUTOAUG: False
  DO_CJ: True
SOLVER:
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 15000
  FREEZE_ITERS: 0
  BASE_LR: 0.0001
  IMS_PER_BATCH: 128
  WARMUP_ITERS: 2000
  DELAY_ITERS: 2000
DATALOADER:
  NUM_INSTANCE: 16
  NUM_WORKERS: 4
DATASETS:
  NAMES: ("SYSUMM01",)
  TESTS: ("SYSUMM01",)
  REGDB_SPLIT_INDEX: 1
TEST:
  FLIP: True
  EVAL_PERIOD: 1001
  PRECISE_BN:
    DATASET: 'Market1501'
  EVASETTING: "SYSU_MM01"
  IMS_PER_BATCH: 384
MUTUAL:
  TYPE: 'SYMMETRIC'
UL:
  CLUSTER:
    TIMES: -1
    STOP: -1