_BASE_: "base.yml"
MUTUAL:
  USE2TEST: True
  TYPE: "ASYMMETRIC"
MODEL:
  BASE: 'BASE'
  HEADS:
    NUM_CLASSES: -1
  LOSSES:
    KL:
      SCALE: 0.1
    SIM:
      SCALE: 0.5
SOLVER:
  MAX_ITER: 15000
  CHECKPOINT_PERIOD: 15000
DATASETS:
  TESTS: ("SYSUMM01",)
  COMBINEALL: False
TEST:
  EVASETTING: "SYSU_MM01"
  EVAL_PERIOD: 20000
  IMS_PER_BATCH: 128
